spring.application.name=IngSistemiWeb_App

# Configurazione MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Web_app
spring.datasource.username=root
spring.datasource.password=Adidati.01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configurazione Thymeleaf ()
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

# Configurazione Email (opzionale)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=matteo03.tosi@edu.unife.it
spring.mail.password=jkdm nzlr voqz qaza
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
